- hosts: host
  become: yes
  vars_files:
  - /opt/mgmt/values.yaml
  tasks:

  # Create custom namespaces

  - name: Create custom namespaces
    shell: "kubectl create namespace {{ item.name }}"
    loop: "{{ custom.namespaces }}"

  - name: Create the Docker Registry pull secret inside all custom namespaces
    shell: "kubectl create -n {{ item.name }} secret docker-registry dockerreg-pull --docker-server=dockerreg.ssp.{{ platform.domain }} --docker-username=admin --docker-password={{ platform.admin.password }} --docker-email={{ platform.email }}"
    loop: "{{ custom.namespaces }}"
